### ISSUE TITLE
Dúvida - setupOnStartup

### ISSUE THREAD

**Issue by patriciasouzas** [miltonhit/hub_correios_api#1]
Oi, Milton. Muito massa esse conteúdo. Obrigada =)
Reproduzi o projeto aqui na minha máquina e me surgiu uma dúvida sobre o que exatamente esse método está fazendo. Olhando a explicação do vídeo não ficou muito clara pra mim.
Se puder tirar essa dúvida, te agradeço.

https://github.com/miltonhit/hub_correios_api/blob/a9210ed41f90883db8ea39d87539f3ba36c932d0/app/src/main/java/br/com/hubia/correios/service/CorreiosService.java#L61

**Comment by miltonhit** [comment]
@patriciasouzas Boa noite! Obrigado pelo feedback :)

Esse método é o responsável por fazer a "instalação do projeto"... Oq isso significa? Quando você liga o projeto a primeira vez, você tem uma base de dados VAZIA, ou seja, a consulta de cep não vai funcionar.

O método "setupOnStartup" vai ser acionado assim que o spring subir, e vai baixar os endereços e coloca-los na base de dados, fazendo assim o "setup" do projeto, deixando ele apto para receber novas requisições.

Espero que tenha ajudado.

**Comment by patriciasouzas** [comment]
@miltonhit ajudou demais, Milton. Muito obrigada!
